Hotfix/start stop with sapcontrol
SUSE/shaptools pull request #55
Opened 2020-09-03 06:49 UTC by arbulu89

Replace `HDB` command usage by `sapcontrol`.

`HDB` command only affects the local machine, and if a multi host environment is used, this causes issues, as it doesn't operated all the machines. Using `sapcontrol` `StartSystem/StopSystem` and the corresponding wait methods fixes this issues, as these actions affect all the hosts in the same site.

I have set the `2700` and `2` values as these are the values used by `HDB`. I don't think adding this values as parameters will help much (adding more complexity). I guess SAP used these values for some good reason.

2020-09-03 10:30 UTC, MalloZup commented on shaptools/hana.py
> +        cmd = 'sapcontrol -nr {} -function WaitforStarted 2700 2'.format(self.inst)
regarding 2700 2 I'm ok if we don't want `paramaters` but right no they are magic number. we should convert this a constants so an user/we can understand what this number are for

`END_OF_WORLD = '2700'`
`HOW_MANY_ALIENS = 2`

2020-09-03 10:30 UTC, MalloZup requested changes
looks good only we should avoid magic numbers and use named constants

2020-09-08 15:00 UTC, Simranpal approved these changes
@arbulu89 Looks good! I could not find the docs for exact/suggested parameters values for `WaitforStarted` sapcontrol. I think based on its usage in the `HDB` script and start sync needed in hana scaleout nodes, we can go ahead with current values.

Other thing I was thinking is if we can have this `function WaitforStarted` as separate method: to wait if hana has started. But the use case maybe not much for now, so this looks fine.

2020-09-10 16:39 UTC, MalloZup approved these changes
sehr gut

2020-09-11 06:22 UTC, merged